# Generated by Django 4.2.16 on 2026-04-29 05:53

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="السنة الدراسية"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="نشطة")),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
            ],
            options={
                "verbose_name": "سنة دراسية",
                "verbose_name_plural": "السنوات الدراسية",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القسم")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز القسم"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "head_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="رئيس القسم"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم الجامعي",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="الاسم الأول"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="اسم الأب"),
                ),
                (
                    "third_name",
                    models.CharField(max_length=100, verbose_name="اسم الجد"),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="الكنية")),
                (
                    "national_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهوية الوطنية"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=students.models.student_photo_path,
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "المرحلة الأولى"),
                            ("2", "المرحلة الثانية"),
                            ("3", "المرحلة الثالثة"),
                            ("4", "المرحلة الرابعة"),
                            ("5", "المرحلة الخامسة"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="المرحلة",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("morning", "صباحي"), ("evening", "مسائي")],
                        default="morning",
                        max_length=10,
                        verbose_name="نوع الدراسة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("suspended", "موقوف"),
                            ("graduated", "متخرج"),
                            ("withdrawn", "منسحب"),
                            ("transferred", "محول"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="المعدل التراكمي",
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(default=0, verbose_name="الساعات المكتسبة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="students.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "entry_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrants",
                        to="students.academicyear",
                        verbose_name="سنة القبول",
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
                "ordering": ["student_id"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id", "صورة الهوية"),
                            ("graduation", "شهادة التخرج"),
                            ("transcript", "كشف الدرجات"),
                            ("medical", "التقرير الطبي"),
                            ("residence", "وثيقة السكن"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الوثيقة"),
                ),
                (
                    "file",
                    models.FileField(upload_to="student_docs/", verbose_name="الملف"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقة طالب",
                "verbose_name_plural": "وثائق الطلاب",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("first", "الفصل الأول"),
                            ("second", "الفصل الثاني"),
                            ("summer", "الدورة الصيفية"),
                        ],
                        max_length=20,
                        verbose_name="الفصل",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                ("is_active", models.BooleanField(default=False, verbose_name="نشط")),
                (
                    "registration_open",
                    models.BooleanField(default=False, verbose_name="التسجيل مفتوح"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="students.academicyear",
                        verbose_name="السنة الدراسية",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["-academic_year__year", "name"],
                "unique_together": {("academic_year", "name")},
            },
        ),
    ]
