# Generated by Django 4.2.16 on 2026-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admission_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="معدل القبول",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="admission_channel",
            field=models.CharField(blank=True, max_length=100, verbose_name="القناة"),
        ),
        migrations.AddField(
            model_name="student",
            name="admission_round",
            field=models.CharField(blank=True, max_length=10, verbose_name="الدور"),
        ),
        migrations.AddField(
            model_name="student",
            name="avg_no_additions",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="المعدل بدون اضافات",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(blank=True, max_length=100, verbose_name="الفرع"),
        ),
        migrations.AddField(
            model_name="student",
            name="exam_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="الرقم الامتحاني"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grad_year_str",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="سنة التخرج"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="health_status",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="الحالية الصحية"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="institute",
            field=models.CharField(blank=True, max_length=100, verbose_name="المعهد"),
        ),
        migrations.AddField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="الحالة الزوجية"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ااسم الام الثلاثي"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="origin_status",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="حالة الطالب (اصيل او وافد)"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="receipt_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الوصل"),
        ),
        migrations.AddField(
            model_name="student",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="رقم الوصل"),
        ),
        migrations.AddField(
            model_name="student",
            name="registration_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="كود التسجيل"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="registration_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ التسجيل"),
        ),
        migrations.AddField(
            model_name="student",
            name="religion",
            field=models.CharField(blank=True, max_length=50, verbose_name="الديانة"),
        ),
        migrations.AddField(
            model_name="student",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="اسم المدرسة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_category",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نوع الطالب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="surname",
            field=models.CharField(blank=True, max_length=100, verbose_name="اللقب"),
        ),
        migrations.AlterField(
            model_name="student",
            name="national_id",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="رقم الهوية/الجواز"
            ),
        ),
    ]
