# Generated by Django 4.2.16 on 2026-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_admission_avg_student_admission_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_round",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "الدور الأول"),
                    ("2", "الدور الثاني"),
                    ("3", "الدور الثالث"),
                    ("تكميلي", "تكميلي"),
                ],
                max_length=10,
                verbose_name="الدور",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("علمي", "علمي"),
                    ("أدبي", "أدبي"),
                    ("احيائي", "احيائي"),
                    ("تطبيقي", "تطبيقي"),
                    ("مهني", "مهني"),
                    ("تجاري", "تجاري"),
                    ("فنون", "فنون"),
                    ("تمريض", "تمريض"),
                ],
                max_length=100,
                verbose_name="الفرع",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("بغداد", "بغداد"),
                    ("البصرة", "البصرة"),
                    ("نينوى", "نينوى"),
                    ("أربيل", "أربيل"),
                    ("النجف الأشرف", "النجف الأشرف"),
                    ("كربلاء المقدسة", "كربلاء المقدسة"),
                    ("ذي قار", "ذي قار"),
                    ("بابل", "بابل"),
                    ("السليمانية", "السليمانية"),
                    ("الأنبار", "الأنبار"),
                    ("ديالى", "ديالى"),
                    ("كركوك", "كركوك"),
                    ("صلاح الدين", "صلاح الدين"),
                    ("المثنى", "المثنى"),
                    ("ميسان", "ميسان"),
                    ("واسط", "واسط"),
                    ("القادسية", "القادسية"),
                    ("دهوك", "دهوك"),
                    ("حلبجة", "حلبجة"),
                ],
                max_length=100,
                verbose_name="المحافظة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="health_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthy", "سليم"),
                    ("special_needs", "ذوي الاحتياجات الخاصة"),
                    ("chronic", "مرض مزمن"),
                ],
                max_length=100,
                verbose_name="الحالية الصحية",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "أعزب/عزباء"),
                    ("married", "متزوج/متزوجة"),
                    ("divorced", "مطلق/مطلقة"),
                    ("widowed", "أرمل/أرملة"),
                ],
                max_length=50,
                verbose_name="الحالة الزوجية",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="origin_status",
            field=models.CharField(
                blank=True,
                choices=[("اصيل", "أصيل"), ("وافد", "وافد")],
                max_length=50,
                verbose_name="حالة الطالب (اصيل او وافد)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muslim", "مسلم"),
                    ("christian", "مسيحي"),
                    ("sabean", "صابئي مندائي"),
                    ("yazidi", "إيزيدي"),
                    ("other", "أخرى"),
                ],
                max_length=50,
                verbose_name="الديانة",
            ),
        ),
    ]
