# Generated by Django 4.2.16 on 2026-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0003_alter_student_admission_round_alter_student_branch_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="department",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="head_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="رئيس القسم"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_channel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="القناة"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_round",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "الدور الأول"),
                    ("2", "الدور الثاني"),
                    ("3", "الدور الثالث"),
                    ("تكميلي", "تكميلي"),
                ],
                max_length=10,
                null=True,
                verbose_name="الدور",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("علمي", "علمي"),
                    ("أدبي", "أدبي"),
                    ("احيائي", "احيائي"),
                    ("تطبيقي", "تطبيقي"),
                    ("مهني", "مهني"),
                    ("تجاري", "تجاري"),
                    ("فنون", "فنون"),
                    ("تمريض", "تمريض"),
                ],
                max_length=100,
                null=True,
                verbose_name="الفرع",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="exam_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="الرقم الامتحاني"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("بغداد", "بغداد"),
                    ("البصرة", "البصرة"),
                    ("نينوى", "نينوى"),
                    ("أربيل", "أربيل"),
                    ("النجف الأشرف", "النجف الأشرف"),
                    ("كربلاء المقدسة", "كربلاء المقدسة"),
                    ("ذي قار", "ذي قار"),
                    ("بابل", "بابل"),
                    ("السليمانية", "السليمانية"),
                    ("الأنبار", "الأنبار"),
                    ("ديالى", "ديالى"),
                    ("كركوك", "كركوك"),
                    ("صلاح الدين", "صلاح الدين"),
                    ("المثنى", "المثنى"),
                    ("ميسان", "ميسان"),
                    ("واسط", "واسط"),
                    ("القادسية", "القادسية"),
                    ("دهوك", "دهوك"),
                    ("حلبجة", "حلبجة"),
                ],
                max_length=100,
                null=True,
                verbose_name="المحافظة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grad_year_str",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="سنة التخرج"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="health_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthy", "سليم"),
                    ("special_needs", "ذوي الاحتياجات الخاصة"),
                    ("chronic", "مرض مزمن"),
                ],
                max_length=100,
                null=True,
                verbose_name="الحالية الصحية",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="institute",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="المعهد"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "أعزب/عزباء"),
                    ("married", "متزوج/متزوجة"),
                    ("divorced", "مطلق/مطلقة"),
                    ("widowed", "أرمل/أرملة"),
                ],
                max_length=50,
                null=True,
                verbose_name="الحالة الزوجية",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ااسم الام الثلاثي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="student",
            name="origin_status",
            field=models.CharField(
                blank=True,
                choices=[("اصيل", "أصيل"), ("وافد", "وافد")],
                max_length=50,
                null=True,
                verbose_name="حالة الطالب (اصيل او وافد)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="receipt_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم الوصل"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="كود التسجيل"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muslim", "مسلم"),
                    ("christian", "مسيحي"),
                    ("sabean", "صابئي مندائي"),
                    ("yazidi", "إيزيدي"),
                    ("other", "أخرى"),
                ],
                max_length=50,
                null=True,
                verbose_name="الديانة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم المدرسة"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نوع الطالب"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اللقب"
            ),
        ),
    ]
