# Generated by Django 4.2.16 on 2026-04-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0004_alter_department_description_alter_department_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="نسبة التخفيض (%)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم ولي الأمر"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "مركزي"),
                    ("parallel", "موازي"),
                    ("private", "أهلي"),
                    ("evening", "مسائي"),
                    ("direct", "مباشر"),
                    ("martyrs", "ذوي الشهداء"),
                    ("talented", "المتميزين"),
                    ("other", "أخرى"),
                ],
                max_length=100,
                null=True,
                verbose_name="القناة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "نشط"),
                    ("initial", "تقديم أولي"),
                    ("suspended", "موقوف"),
                    ("graduated", "متخرج"),
                    ("withdrawn", "منسحب"),
                    ("transferred", "محول"),
                ],
                default="active",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("id", "صورة الهوية"),
                    ("graduation", "شهادة التخرج"),
                    ("transcript", "كشف الدرجات"),
                    ("medical", "التقرير الطبي"),
                    ("residence", "وثيقة السكن"),
                    ("discount", "وثيقة التخفيض"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع الوثيقة",
            ),
        ),
        migrations.CreateModel(
            name="StudentPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_level",
                    models.CharField(
                        choices=[
                            ("1", "المرحلة الأولى"),
                            ("2", "المرحلة الثانية"),
                            ("3", "المرحلة الثالثة"),
                            ("4", "المرحلة الرابعة"),
                            ("5", "المرحلة الخامسة"),
                        ],
                        max_length=1,
                        verbose_name="من المرحلة",
                    ),
                ),
                (
                    "to_level",
                    models.CharField(
                        choices=[
                            ("1", "المرحلة الأولى"),
                            ("2", "المرحلة الثانية"),
                            ("3", "المرحلة الثالثة"),
                            ("4", "المرحلة الرابعة"),
                            ("5", "المرحلة الخامسة"),
                        ],
                        max_length=1,
                        verbose_name="إلى المرحلة",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "ناجح"),
                            ("referred", "مكمل"),
                            ("failed", "راسب"),
                            ("decision", "ناجح بقرار"),
                            ("carry_over", "تحميل"),
                        ],
                        max_length=20,
                        verbose_name="النتيجة",
                    ),
                ),
                (
                    "promotion_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الترحيل"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.academicyear",
                        verbose_name="السنة الدراسية",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ترحيل طالب",
                "verbose_name_plural": "ترحيلات الطلاب",
                "ordering": ["-promotion_date"],
            },
        ),
    ]
