# Generated by Django 4.2.16 on 2026-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0005_student_discount_percentage_student_guardian_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "نشط"),
                    ("initial", "تقديم أولي"),
                    ("suspended", "موقوف"),
                    ("graduated", "متخرج"),
                    ("withdrawn", "منسحب"),
                    ("transferred", "محول"),
                ],
                default="initial",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
