# Generated by Django 4.2.30 on 2026-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="has_foreign_language",
            field=models.BooleanField(default=False, verbose_name="يملك لغة أجنبية"),
        ),
        migrations.AddField(
            model_name="student",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="التخصص"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("علمي", "علمي"),
                    ("أدبي", "أدبي"),
                    ("احيائي", "احيائي"),
                    ("تطبيقي", "تطبيقي"),
                    ("مهني", "مهني"),
                    ("تجاري", "تجاري"),
                    ("فنون", "فنون"),
                    ("تمريض", "تمريض"),
                    ("زراعي", "زراعي"),
                    ("حاسوب تقنيات المعلومات", "حاسوب تقنيات المعلومات"),
                    ("فنون تطبيقية", "فنون تطبيقية"),
                    ("معهد اعداد معلمين", "معهد اعداد معلمين"),
                    ("مفوضيه الشرطه", "مفوضيه الشرطه"),
                    ("معهد السياحه والفندقه", "معهد السياحه والفندقه"),
                    ("فنون جميله ابطال", "فنون جميله ابطال"),
                    ("خريج تدريب مهني معهد سكك", "خريج تدريب مهني معهد سكك"),
                ],
                max_length=100,
                null=True,
                verbose_name="الفرع",
            ),
        ),
    ]
