# Generated by Django 4.2.30 on 2026-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0007_student_has_foreign_language_student_specialization_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="health_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthy", "سليم"),
                    ("special_needs", "ذوي الاحتياجات الخاصة"),
                    ("chronic", "مرض مزمن"),
                ],
                max_length=100,
                null=True,
                verbose_name="الحالة الصحية",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم الأم الثلاثي"
            ),
        ),
    ]
