# Generated by Django 4.2.30 on 2026-05-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_student_health_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="الملاحظة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="بواسطة"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة طالب",
                "verbose_name_plural": "ملاحظات الطلاب",
                "ordering": ["-created_at"],
            },
        ),
    ]
