# Generated by Django 4.2.30 on 2026-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_studentnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="archive_locker",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="موقع الأرشيف الورقي (الوكر/الدرج)",
            ),
        ),
    ]
