# Generated by Django 4.2.7 on 2026-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_student_archive_locker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الكنية"
            ),
        ),
    ]
