# Generated by Django 4.2.16 on 2026-06-15 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_alter_student_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="محل الولادة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="citizenship",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الجنسية"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_death_certificate",
            field=models.BooleanField(default=False, verbose_name="شهادة الوفاة"),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_grade_confirmation",
            field=models.BooleanField(default=False, verbose_name="تأييد الدرجات"),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_medical_exam",
            field=models.BooleanField(default=False, verbose_name="الفحص الطبي"),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_national_id_father",
            field=models.BooleanField(
                default=False, verbose_name="البطاقة الوطنية للأب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_national_id_mother",
            field=models.BooleanField(
                default=False, verbose_name="البطاقة الوطنية للأم"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_national_id_student",
            field=models.BooleanField(
                default=False, verbose_name="البطاقة الوطنية للطالب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_personal_photos",
            field=models.BooleanField(default=False, verbose_name="الصور الشخصية"),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_residence_card",
            field=models.BooleanField(default=False, verbose_name="بطاقة السكن"),
        ),
        migrations.AddField(
            model_name="student",
            name="doc_sponsor",
            field=models.BooleanField(default=False, verbose_name="الكفيل"),
        ),
        migrations.AddField(
            model_name="student",
            name="document_auth",
            field=models.CharField(
                blank=True,
                choices=[("certified", "مصادقة"), ("not_certified", "غير مصادقة")],
                max_length=20,
                null=True,
                verbose_name="مصادقة الوثيقة",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="document_receipt",
            field=models.CharField(
                choices=[("present", "موجودة"), ("not_present", "غير موجودة")],
                default="not_present",
                max_length=20,
                verbose_name="استلام الوثيقة",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ethnicity",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="القومية"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="المجموع",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "عامة"),
                    ("social_care", "رعاية اجتماعية"),
                    ("evening", "مسائي"),
                    ("martyrs", "ذوي الشهداء"),
                    ("talented", "المتميزين"),
                    ("other", "أخرى"),
                ],
                max_length=100,
                null=True,
                verbose_name="القناة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يتكون من 11 رقماً فقط (مثل: 07701234567).",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="رقم ولي الأمر",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الاسم الرابع"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يتكون من 11 رقماً فقط (مثل: 07701234567).",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
