# Generated by Django 4.2.7 on 2026-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_student_birth_place_student_citizenship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="archive_locker",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="موقع الأرشيف الورقي (اللوكر/الخزانة)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_place",
            field=models.CharField(
                blank=True,
                choices=[
                    ("بغداد", "بغداد"),
                    ("البصرة", "البصرة"),
                    ("نينوى", "نينوى"),
                    ("أربيل", "أربيل"),
                    ("النجف الأشرف", "النجف الأشرف"),
                    ("كربلاء المقدسة", "كربلاء المقدسة"),
                    ("ذي قار", "ذي قار"),
                    ("بابل", "بابل"),
                    ("السليمانية", "السليمانية"),
                    ("الأنبار", "الأنبار"),
                    ("ديالى", "ديالى"),
                    ("كركوك", "كركوك"),
                    ("صلاح الدين", "صلاح الدين"),
                    ("المثنى", "المثنى"),
                    ("ميسان", "ميسان"),
                    ("واسط", "واسط"),
                    ("القادسية", "القادسية"),
                    ("دهوك", "دهوك"),
                    ("حلبجة", "حلبجة"),
                    ("خارج العراق", "خارج العراق"),
                ],
                max_length=150,
                null=True,
                verbose_name="محل الولادة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="citizenship",
            field=models.CharField(
                blank=True,
                choices=[("عراقي", "عراقي"), ("أجنبي", "أجنبي")],
                max_length=100,
                null=True,
                verbose_name="الجنسية",
            ),
        ),
    ]
