# Generated by Django 4.2.16 on 2026-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_name",
                    models.CharField(
                        default="الجامعة التقنية",
                        max_length=200,
                        verbose_name="اسم الجامعة/الكلية",
                    ),
                ),
                (
                    "college_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الكلية"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="system/",
                        verbose_name="شعار الجامعة",
                    ),
                ),
                (
                    "header_color",
                    models.CharField(
                        default="#1a237e",
                        max_length=20,
                        verbose_name="لون الهوية الأساسي",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد التواصل"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
    ]
