# Generated by Django 4.2.30 on 2026-05-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "تسجيل دخول"),
                            ("logout", "تسجيل خروج"),
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                ("details", models.TextField(verbose_name="التفاصيل")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل النظام",
                "verbose_name_plural": "سجل النظام",
                "ordering": ["-timestamp"],
            },
        ),
    ]
