# Generated by Django 4.2.30 on 2026-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الدليل"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="يمكنك استخدام HTML لتنسيق النص",
                        verbose_name="تعليمات القبول",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="guides/",
                        verbose_name="ملف الدليل (PDF)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "دليل وضوابط القبول",
                "verbose_name_plural": "أدلة وضوابط القبول",
            },
        ),
    ]
