# Generated by Django 4.2.7 on 2026-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_admissionguide"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("governorate", "المحافظات"),
                            ("religion", "الأديان"),
                            ("health_status", "الحالة الصحية"),
                            ("branch", "الفروع الدراسية"),
                            ("origin_status", "حالة الطالب أصيل/وافد"),
                            ("admission_channel", "قنوات القبول"),
                            ("marital_status", "الحالة الزوجية"),
                            ("gender", "الجنس"),
                            ("level", "المراحل الدراسية"),
                            ("study_type", "نوع الدراسة"),
                            ("status", "حالة الطالب (نشط/موقوف/إلخ)"),
                            ("citizenship", "الجنسية"),
                            ("birth_place", "محل الولادة"),
                        ],
                        max_length=50,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=100, verbose_name="القيمة (بالقاعدة)"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=150, verbose_name="الاسم المعروض"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "خيار ديناميكي",
                "verbose_name_plural": "الخيارات الديناميكية",
                "ordering": ["category", "display_name"],
                "unique_together": {("category", "value")},
            },
        ),
    ]
