# Generated by Django 4.2.16 on 2026-04-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم التتبع",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "تأييد دراسي"),
                            ("graduation_doc", "وثيقة تخرج"),
                            ("transcript", "كشف درجات"),
                            ("certificate", "إفادة طالب"),
                            ("postpone", "طلب تأجيل"),
                            ("withdrawal", "طلب انسحاب"),
                            ("transfer", "طلب نقل"),
                            ("re_enrollment", "طلب إعادة قيد"),
                            ("excuse", "طلب عذر"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=300, verbose_name="الاسم الرباعي"),
                ),
                (
                    "student_id_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الرقم الجامعي"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهوية الوطنية"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=200, verbose_name="القسم"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "المرحلة الأولى"),
                            ("2", "المرحلة الثانية"),
                            ("3", "المرحلة الثالثة"),
                            ("4", "المرحلة الرابعة"),
                            ("5", "المرحلة الخامسة"),
                        ],
                        max_length=1,
                        verbose_name="المرحلة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="تفاصيل الطلب"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="service_requests/attachments/",
                        verbose_name="ملف مرفق",
                    ),
                ),
                (
                    "webcam_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_requests/webcam/",
                        verbose_name="صورة من الكاميرا",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("reviewing", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("completed", "مكتمل"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="تمت المراجعة بواسطة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقديم"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "طلب طالب",
                "verbose_name_plural": "طلبات الطلاب",
                "ordering": ["-created_at"],
            },
        ),
    ]
