# Generated by Django 4.2.16 on 2026-04-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentrequest",
            name="department_name",
        ),
        migrations.AddField(
            model_name="studentrequest",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="students.department",
                verbose_name="القسم",
            ),
        ),
    ]
