# Generated by Django 4.2.16 on 2026-04-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_studentrequest_department_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="السؤال")),
                ("answer", models.TextField(verbose_name="الإجابة")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سؤال شائع",
                "verbose_name_plural": "الأسئلة الشائعة",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
