# Generated by Django 4.2.16 on 2026-06-15 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_studentrequest_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequest",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يتكون من 11 رقماً فقط (مثل: 07701234567).",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "تأييد دراسي"),
                    ("graduation_doc", "وثيقة تخرج"),
                    ("transcript", "كشف درجات"),
                    ("certificate", "تاييد طالب"),
                    ("postpone", "طلب تأجيل"),
                    ("withdrawal", "طلب انسحاب"),
                    ("transfer", "طلب نقل"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
    ]
